---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootesss
  labels:
    app: springbootesss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootesss
  template:
    metadata:
      labels:
        app: springbootesss
    spec:
      containers:
        - name: springbootesss
          image: docker.io/phengbunath/springbootesss:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
